#!/usr/bin/env sh
# shellcheck disable=all
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged
npm run check # {...if you want to commit anyway, something like} || echo "npm run check returned errors. Committing anyway..."
